### PR TITLE
Add TypeScript typings

### LINKED ISSUE #45: TypeScript definitions
Could you add types / TypeScript definitions?

### PR DESCRIPTION
**Pull request by KnorpelSenf**
This PR migrates the library to TypeScript. All basic types are provided, however, while this already helps a lot, a few things could still be improved. Contributions are welcome:
1) Callbacks are generally just typed `Function`. This could be improved by specifying the exact types the callback takes (and returns). [UPDATE: done]
1) API requests return `any`. This means that neither jobs nor tasks have their own `interface`s, as they should have. [UPDATE: done]

Furthermore, this PR fixes a typo that caused roughly 50 % of the integration tests to fail. When applying this PR, all tests (both unit and integration) pass again.

Another small change I applied is to use the recommended `Map` instead of a POJO to hold the subscribed channels. It does not change anything about the behaviour of this library, though. It mainly improves the typing.

Note that I actively use this updated version of the library in a personal TypeScript project. I did not experience any problems with it so far, but of course I would keep on improving this library in case I find a bug or something else that is annoying.

Closes #45.

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
I should add that I bumped the `mocha` dev dependency by two major versions in order to fix a few security vulnerabilities. This was an automatic suggestion by running `npm audit fix --force`.

**Comment by josiasmontag** [comment]
Thanks a lot for your work on this!

Is this backward compatible? It seems `main` and `module` in package.json do point to non existing files? 
Also, `types` and `prepublish` seem to be missing in package.json?

Could you update the README on how to use this in a TypeScript project?

Sorry for all these questions - I have never published a TypeScript package on NPM before.

**Comment by KnorpelSenf** [comment]
Thank you for coming back to this. Accepting the PR *should* keep the package backwards compatible. However, I'm not yet 100 % certain that this is the case, so thanks for reviewing the work!

You are very right with the `package.json`, updating this file slipped through. This should be changed from `lib` to `built` in order to point to the output folder. I also added the `types` and the `prepublish` properties.

I also updated the README so other people can reproduce the build step. Checking backwards compatibility needs some testing. I cloned your [CLI](https://github.com/cloudconvert/cloudconvert-cli) and made it rely on the typed version without touching the source code. This worked without problems, but I would appreciate if you could run a similar experiment to increase the confidence.

**Comment by KnorpelSenf** [comment]
Two more things: I did not write anything about how to use this in a TS project because this is generally not necessary. It just works. If someone uses it in a TS project as of today, the compiler will issue a warning that no types can be found. It suggests to install them from DefinitelyTyped, unfortunately, they are not present there. Consequently, every user of this library would have to add custom type definition files (or silence the compiler instead). That's why I submitted this PR in the first place.

The other thing really is a minor change to `package.json`. When executing an npm script, the `./node_modules/.bin/` directory is implicitly added to the PATH variable. As a result, it is possible to just execute `mocha` right away, there's no need to start `node ./node_modules/.bin/ mocha`. I therefore simplified the testing scripts. (I don't want this change to go unnoticed.)

**Comment by Suyashtnt** [comment]
does not work, `Could not find a declaration file for module 'cloudconvert'. 'c:/Users/Home/Documents/EmojiBoi/node_modules/cloudconvert/built/index.js' implicitly has an 'any' type.
  Try `npm install @types/cloudconvert` if it exists or add a new declaration (.d.ts) file containing `declare module 'cloudconvert';``

**Comment by KnorpelSenf** [comment]
Note that the PR is not merged yet. It is necessary to build the source code from my fork of this repo, i.e. create a fresh directory and run
```bash
git clone git@github.com:KnorpelSenf/cloudconvert-node.git
cd cloudconvert-node
npm install
npm run build
sudo npm link
```
Now go to some other project that uses cloudconvert, for example the one where you got you error message from, and run
```bash
npm remove cloudconvert
npm link cloudconvert
```

Next, check again if the types are still missing.

**Comment by Suyashtnt** [comment]
image
not working when i try to create a job

**Comment by KnorpelSenf** [comment]
Thank you for the valuable feedback!

I can see that the TypeScript integration works as expected—just the types need further development. I will take care of the issue in the coming days when I work on the aforementioned types that are still missing (jobs/tasks and callbacks)

**Comment by KnorpelSenf** [comment]
I added all missing types. As a result, we now have full type safety across the entire API. There are a few tiny things that need to be done before this can finally be merged:
- @josiasmontag please check out #47
- `await cloudconvert.tasks.upload` still returns `any` because I do not really understand what's happening there
- @Suyashtnt please pull in the fresh types—does it work as expected now?

**Comment by KnorpelSenf** [comment]
That's it from my side for now, the migration to TS should be done IMO. Don't hesitate to comment or ask any question. Otherwise I'll be waiting for this to be merged.

**Comment by josiasmontag** [comment]
@Suyashtnt Can you check if this PR works for you?

**Comment by KnorpelSenf** [comment]
In order to verify independently that the library still works after the rewrite, consider performing these steps.

```bash
# Make sure you have a local version of the fork installed
mkdir /tmp/cloudconvert-node-typescript-rewrite-test/
cd !$
git clone git@github.com:KnorpelSenf/cloudconvert-node.git
cd cloudconvert-node
npm install
npm run build
```

You will need to execute
```bash
sudo npm link
```
with `sudo` rights in the same directory and continue with:

```bash
# Create and compile sample project from scratch
mkdir /tmp/cloudconvert-node-typescript-rewrite-test/my-project/
cd !$
npm init -y
npm install typescript --save-dev
npm link cloudconvert
echo -e "import CloudConvert from 'cloudconvert';\n\n// taken from integration tests\nconst apiKey = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjI4YmE3OGQyZjc1NWM5ZGE3Yjg1NDRhMWRkMjg2NWM4N2U0YzI5NWI0NzQ0Zjc4ZDNmMzA3OWM2NjU3ZjI0MjVhOTMyYjIxMjU5ZGU2NWQ4In0.eyJhdWQiOiIxIiwianRpIjoiMjhiYTc4ZDJmNzU1YzlkYTdiODU0NGExZGQyODY1Yzg3ZTRjMjk1YjQ3NDRmNzhkM2YzMDc5YzY2NTdmMjQyNWE5MzJiMjEyNTlkZTY1ZDgiLCJpYXQiOjE1NTkwNjc3NzcsIm5iZiI6MTU1OTA2Nzc3NywiZXhwIjo0NzE0NzQxMzc3LCJzdWIiOiIzNzExNjc4NCIsInNjb3BlcyI6WyJ1c2VyLnJlYWQiLCJ1c2VyLndyaXRlIiwidGFzay5yZWFkIiwidGFzay53cml0ZSIsIndlYmhvb2sucmVhZCIsIndlYmhvb2sud3JpdGUiXX0.IkmkfDVGwouCH-ICFAShQMHyFAHK3y90CSoissUVD8h5HFG4GqN5DEw0IFzlPr1auUKp3H1pAvPutdIQtrDMTmUUmGMUb2dRlCAuQdqxa81Q5KAmcKDgOg2YTWOWEGMy3jETTb7W6vyNGsT_3DFMapMdeOw1jdIUTMZqW3QbSCeGXj3PMRnhI7YynaDtmktjzO9IUDHbeT2HRzzMiep97KvVZNjYtZvgM-kbUjE6Mm68_kA8JMuQeor0Yg7896JPV0YM3-MnHf7elKgoCJbfBCDAbvSX_ZYsSI7IGoLLb0mgJVfFcH_HMYAHhJj5cUEJN2Iml-FkODqrRk72bVxyJs9j1GPQBl4ORXuU9yrjUgHrRaZ5YM__LwsUQB3AuB92oyQseCjULn1sWM1PzIXCcyVjKZSpn9LAAGNf9paCF-_G9ok9tZKccRouCiYl9v5XbmuxV8hXYp6fXZxyaAkj_JN2kErVSkxYzVyyZL1e220aFFnbch6nDvLFHgi-WeTQHFQDzuHsM8RKRixV8uD7pk3de4AEYg0EWqZHCr82qY7TGdSQvuAS0QIy3B89OwQW0ROW4k3Yw0XIKgKSYWyKnc7huc7yPQUIDDDAOa5OojXrVY5ZuL_hwQMIOmejcHTKFdAgzAaVnRkC8_FfVh4wHCPBaHjze9hRp5n4O1pnPFI';\n\nconst cloudConvert = new CloudConvert(apiKey, true);\ncloudConvert.users.me().then(console.log);" > index.ts
npx tsc --esModuleInterop index.ts
node .
```

Please verify that the output looks like this:

```js
{
  id: 37116784,
  username: 'CloudConvert-OS',
  email: 'support@cloudconvert.com',
  created_at: '2019-05-28T18:22:10+00:00',
  credits: 1000,
  paying: false,
  priority: -10,
  links: { self: 'https://api.sandbox.cloudconvert.com/v2/users/37116784' }
}
```

You have now compiled and run a sample project.

You may want to reuse this project to explore the other types of the PR (VSCode?). For example, try to copy & paste the example code for job creation from the README and convince yourself that the types are correct and the project still compiles. Furthermore, you will be able to see error messages when adding invalid properties to the object that is passed to `cloudconvert.jobs.create` (here I added a field with key `redirect` to an `import/url` task where this is not supported):

> ```bash
>   Object literal may only specify known properties, and ''redirect'' does not exist in type 'TaskTemplate<"import/url">'.
> 
> 14             'redirect': 'https://www.cloudconvert.com/'
>                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
>

**Comment by KnorpelSenf** [comment]
@josiasmontag thank you for reviewing and merging! That's great :)

**Pull request merged**
